apiVersion: apps/v1
kind: Deployment
metadata:
  name: eranin-pdf-co
  namespace: eranin-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eranin-pdf-co
  template:
    metadata:
      labels:
        app: eranin-pdf-co
    spec:
      containers:
        - name: eranin-pdf-co
          image: vcr.vngcloud.vn/105586-eranin-prod-02/eranin-pdf-co:latest
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: eranin-pdf-co
  namespace: eranin-prod
spec:
  type: NodePort
  selector:
    app: eranin-pdf-co
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30023
